<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_priceitem</name>
   <tag></tag>
   <elementGuidId>e43d6e14-3b4f-4a17-b1ca-ed29049899ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='priceitem'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ce0fbe21-3666-4f11-aaa7-928521092503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>748188f6-9200-4e1d-aac7-01d98250a553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>priceitem</value>
      <webElementGuid>a5963a6e-3b3f-4c48-9528-56f30e892e03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>iphone-15-pro-128gb-23091305493850</value>
      <webElementGuid>f8c99dae-1d29-4c7b-b6fd-ef4de6a91ab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninvalid</name>
      <type>Main</type>
      <value>this.setCustomValidity('Vui lòng chọn')</value>
      <webElementGuid>e843cc6f-ed1d-4110-8ba4-c972d87fe7a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-products prodetail browser__chrome browser__linux pageis-sticky&quot;]/aside[@class=&quot;clearfix pagemain-wrapper&quot;]/div[@class=&quot;container wrapper-container prodetail__main prodetail__18712&quot;]/div[@class=&quot;pdinfo_faddcart detail_pdinfo_faddcart&quot;]/form[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-lg-12 col-xl-9&quot;]/div[@class=&quot;prodetail__wrapper prodetail__overview_imginfo row mx-0 mb-0&quot;]/div[@class=&quot;col-12 col-lg prodetail__overview_info pb-0 pb-md-4&quot;]/fieldset[@class=&quot;proprice_group proprice_color_group&quot;]/div[@class=&quot;row proprice_color_group_listcolor&quot;]/div[@class=&quot;col proprice_item proprice_item--img&quot;]/label[@class=&quot;transition proprice_action&quot;]/input[1]</value>
      <webElementGuid>d9ca3f82-2a04-495b-8a62-8680f86bd12d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='priceitem'])[3]</value>
      <webElementGuid>e4310d0a-bfc6-4cba-984d-5968c64695ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label/input</value>
      <webElementGuid>57474cd1-c067-49b8-b601-47f888715aca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'priceitem']</value>
      <webElementGuid>3be929dd-df41-40b0-8784-2305aee6744e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
