<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_iPhone 15 Pro 128GB product name</name>
   <tag></tag>
   <elementGuidId>72893581-5848-4a8f-abf9-31c080e507ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='getproduct_reponse']/div/div/div/a/div[2]/h3</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h3.probox__title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>f566f812-9b9c-40f7-89cf-fa76f08a86e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>probox__title</value>
      <webElementGuid>fdab224a-ac28-4f3e-b33b-61a82f2fd1e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>iPhone 15 Pro 128GB - Chính hãng VN/A</value>
      <webElementGuid>67bc995d-2bec-45c3-ba5e-fc4cd0fb8ffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;getproduct_reponse&quot;)/div[@class=&quot;row row-cols-2 row-cols-sm-4 row-cols-lg-5 row-cols-xl-5 product__container&quot;]/div[@class=&quot;col proitem&quot;]/div[@class=&quot;probox  boxproid__18712 boxprobrand__apple boxprotype__product pro__group86 pro__main1487 prothreaduudai--440 prolink--516  probox__text_promotion_18712 probox--pricemin-5 probox--pricemin-10 probox--pricemin-20 probox--appearance probox-appearance-583 probox--tratruoc&quot;]/a[@class=&quot;box&quot;]/div[@class=&quot;probox__des is-countdown&quot;]/h3[@class=&quot;probox__title&quot;]</value>
      <webElementGuid>152f7f65-0ec8-4670-94d0-eaa98aaca1c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='getproduct_reponse']/div/div/div/a/div[2]/h3</value>
      <webElementGuid>fb1ca3f9-4ed5-40af-932b-f3cc51962af4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>7b5401c5-79a8-4cc8-9298-4487911d7004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'iPhone 15 Pro 128GB - Chính hãng VN/A' or . = 'iPhone 15 Pro 128GB - Chính hãng VN/A')]</value>
      <webElementGuid>1b031f17-30ce-48c5-b4bf-ae41a68ab469</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
