<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Trash</name>
   <tag></tag>
   <elementGuidId>a698e0c0-8fbe-4ee9-9ac6-b737093c3d75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.col-auto.ms-auto.btn.btn-sm.btn-light.border.hover.cartbtn_removeitem</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bfcbd2c3-9cf6-406e-9439-e99199d0cb65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f6e495f4-6b29-4ee4-b669-36ee2d021ed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-checkin</name>
      <type>Main</type>
      <value>c52ebd9ef5cdf82c4348a83b527159ec</value>
      <webElementGuid>258d15f6-a8b8-4034-abb7-a363925213cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-auto ms-auto btn btn-sm btn-light border hover cartbtn_removeitem</value>
      <webElementGuid>73d766ae-a3e5-4f33-b1c8-ae2a1c35f374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-confirm</name>
      <type>Main</type>
      <value>Bạn muốn xoá SP này khỏi đơn đặt hàng.</value>
      <webElementGuid>8493d763-a829-4922-b3a2-750dc75a832d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart_content&quot;)/div[@class=&quot;cartitem row cartitem_c52ebd9ef5cdf82c4348a83b527159ec cartitem--productpricecolor&quot;]/div[@class=&quot;product px-0 row col flex-column&quot;]/div[@class=&quot;product_info col&quot;]/h5[@class=&quot;title d-flex flex-nowrap align-items-start&quot;]/button[@class=&quot;col-auto ms-auto btn btn-sm btn-light border hover cartbtn_removeitem&quot;]</value>
      <webElementGuid>62fe8007-348c-4a85-818e-c91840719051</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>98b48ae1-4a88-4dba-a4b0-038b1e636b19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cart_content']/div/div[2]/div/h5/button</value>
      <webElementGuid>490670e8-c4b4-4269-af75-0621214f80dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h5/button</value>
      <webElementGuid>09325956-9f5f-4900-9d39-7be4bc8a90cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>60f9ca96-bfee-4569-be2a-74dc75721186</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
